"""
Reporter Agent - Generates reports in various formats.
"""

import json
from datetime import datetime
from pathlib import Path

from .base import ProcessorAgent, NewsItem


class ReporterAgent(ProcessorAgent):
    """
    Agent for generating reports from analyzed items.

    Supported formats:
    - Markdown
    - Plain text
    - JSON
    """

    def __init__(self, config: dict = None):
        super().__init__("reporter", config)

    def process(self, items: list[NewsItem]) -> list[NewsItem]:
        """Generate report and return items unchanged."""
        # This agent doesn't modify items, just generates report
        return items

    def run(self, task: dict = None) -> dict:
        """Generate report from items."""
        items_data = task.get('items', []) if task else []
        items = [NewsItem.from_dict(i) for i in items_data]

        format_type = task.get('format', 'markdown') if task else 'markdown'
        output_path = task.get('output_path') if task else None

        self.log_info(f"Generating {format_type} report for {len(items)} items...")

        try:
            report = self.generate_report(items, format_type)

            result = {
                "status": "success",
                "agent": self.name,
                "format": format_type,
                "report": report
            }

            if output_path:
                self._save_report(report, output_path)
                result["output_path"] = output_path

            return result
        except Exception as e:
            self.log_error(f"Report generation failed: {e}")
            return {
                "status": "error",
                "agent": self.name,
                "error": str(e)
            }

    def generate_report(self, items: list[NewsItem], format_type: str = 'markdown') -> str:
        """Generate report in specified format."""
        if format_type == 'markdown':
            return self._generate_markdown(items)
        elif format_type == 'json':
            return self._generate_json(items)
        else:
            return self._generate_text(items)

    def _generate_markdown(self, items: list[NewsItem]) -> str:
        """Generate Markdown report."""
        components = ', '.join(self.get_config('components', ['all']))

        lines = [
            "# LLVM Monitor Report",
            "",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"**Updates found:** {len(items)}",
            f"**Tracked components:** {components}",
            "",
        ]

        # Group by importance
        high = [i for i in items if i.importance == 'high']
        medium = [i for i in items if i.importance == 'medium']
        low = [i for i in items if i.importance == 'low']

        if high:
            lines.append("## High Priority - Action Required")
            lines.append("")
            for item in high:
                lines.extend(self._format_item_md(item))

        if medium:
            lines.append("## Medium Priority - Worth Reviewing")
            lines.append("")
            for item in medium:
                lines.extend(self._format_item_md(item))

        if low:
            lines.append("## Low Priority - Informational")
            lines.append("")
            for item in low[:15]:
                lines.extend(self._format_item_md(item))
            if len(low) > 15:
                lines.append(f"*... and {len(low) - 15} more updates*")
                lines.append("")

        if not items:
            lines.append("*No new updates*")

        # Add footer
        lines.extend([
            "",
            "---",
            f"*Generated by LLVM Monitor Multi-Agent System*"
        ])

        return '\n'.join(lines)

    def _format_item_md(self, item: NewsItem) -> list[str]:
        """Format a single item as Markdown."""
        lines = [
            f"### [{item.title}]({item.url})",
            "",
            f"- **Source:** {item.source}",
        ]
        if item.date:
            lines.append(f"- **Date:** {item.date}")
        if item.tags:
            lines.append(f"- **Tags:** {', '.join(item.tags)}")
        if item.summary:
            lines.append("")
            lines.append(f"> {item.summary[:300]}")
        lines.append("")
        return lines

    def _generate_text(self, items: list[NewsItem]) -> str:
        """Generate plain text report."""
        lines = [
            "=" * 60,
            "LLVM MONITOR REPORT",
            f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"Found: {len(items)} updates",
            "=" * 60,
            "",
        ]

        for item in items:
            icon = {'high': '[!!!]', 'medium': '[!!]', 'low': '[i]'}[item.importance]
            lines.append(f"{icon} [{item.source}] {item.title}")
            lines.append(f"    URL: {item.url}")
            if item.summary:
                lines.append(f"    {item.summary[:100]}...")
            lines.append("")

        return '\n'.join(lines)

    def _generate_json(self, items: list[NewsItem]) -> str:
        """Generate JSON report."""
        report = {
            "meta": {
                "date": datetime.now().isoformat(),
                "total_items": len(items),
                "high_priority": sum(1 for i in items if i.importance == 'high'),
                "medium_priority": sum(1 for i in items if i.importance == 'medium'),
                "low_priority": sum(1 for i in items if i.importance == 'low'),
            },
            "items": [item.to_dict() for item in items]
        }
        return json.dumps(report, indent=2, ensure_ascii=False)

    def _save_report(self, report: str, path: str):
        """Save report to file."""
        filepath = Path(path)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(report)
        self.log_info(f"Report saved to: {path}")
